### ISSUE TITLE
Some Difficulty using the Filter

### ISSUE THREAD

**Issue by globsecure** [rmasters/filter#1]
I'm having some difficulty using the filter, when I'm running him en masse in the Model, you would have a code sample using the same?

**Comment by rmasters** [comment]
Hi there,

Do you mean setting values in mass-assignment? i.e. `new Model(array(...))` or `$model->fill(array(...))`? I've just [added some tests for this](https://github.com/rmasters/filter/blob/develop/tests/Filter/HasFiltersTest.php#L75) and it seems to work.

If you're after a usage example, have a look at the [model test](https://github.com/rmasters/filter/blob/master/tests/Filter/HasFiltersTest.php#L5) - I'll try and simplify the readme sometime.
